### ISSUE TITLE
CWBI-OPS Code Migration

### ISSUE THREAD

**Issue by stevendriley** [cwbi-apps/access-request#14]
## Module Name
CWBI-OPS

## Platform 1 or GitHub repository link(s) - note if archive only
https://code.il2.dso.mil/platform-one/products/cwbi/cwbi-ops/cwbi-ops-apex
https://code.il2.dso.mil/platform-one/products/cwbi/cwbi-ops/cwbi-ops-database

https://code.il2.dso.mil/platform-one/products/cwbi/cwbi-ops/ombil-legacy  - Archive Only
https://code.il2.dso.mil/platform-one/products/cwbi/cwbi-ops/legacy - Archive Only
https://code.il2.dso.mil/platform-one/products/cwbi/cwbi-ops/apex-office-print - Archive Only

## Module Admin(s): name - username
Steven D Riley - stevendriley

**Comment by ajbuchanjr** [comment]
Also want to pull over https://code.il2.dso.mil/platform-one/products/cwbi/cwbi-ops/cwbi-airflow-docker

Team GitHub Handles:
ajbuchanjr
mjparker-bah-usace
jtsenkbeil-bah-usace

May have one more once Tony Miller is back tomorrow.

**Comment by willbreitkreutz** [comment]
@ajbuchanjr and @stevendriley 
I created the repos, I did name legacy -> cwbi-ops-legacy to make it more apparent what it is (let me know if that's not right)
and i named the apex-office-print repo -> cwbi-ops-apex-office-print since i think there are others using AOP so didn't want that to be confusing.

oh, also, cwbi-airflow-docker is now cwbi-ops-airflow-docker to distinguish it from other airflow projects.

Once the code is pushed i can mark the archive repos accordingly.

Thanks,
Will
